Repository PenDZ-Alter/kel7_mobile, pull requests merged in 2024-09, with the labels that each got.

#2 Commands was Removed
  lib/main.dart
Labels: documentation

#4 chore: remove unnecessary component
  analysis_options.yaml
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation

#5 Switching to OOP style
  lib/home.dart
  lib/main.dart
Labels: documentation

#7 fix(fonts): using custom fonts
  assets/fonts/times_new_roman.ttf
  assets/fonts/times_new_roman_bold.ttf
  assets/fonts/times_new_roman_bold_italic.ttf
  assets/fonts/times_new_roman_italic.ttf
  lib/home.dart
  pubspec.yaml
Labels: bug

#8 Adding Components
  lib/home.dart
  lib/main.dart
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement

#9 Refactoring Codes
  lib/home.dart
  pubspec.yaml
Labels: documentation

#10 Features and Fix : Image context and scrollbar function
  assets/Images/Hamilton.jpg
  lib/home.dart
  lib/main.dart
  pubspec.yaml
Labels: bug, enhancement

#11 Simplify Code
  lib/home.dart
Labels: documentation, enhancement

#12 add features
  assets/Images/Ticket.png
  assets/Images/hamilton_logo2.png
  lib/home.dart
  lib/login.dart
  lib/main.dart
  pubspec.yaml
Labels: bug, documentation, enhancement

#14 Re-merge codes
  lib/home.dart
  pubspec.yaml
Labels: documentation, enhancement

#15 feat: Add image and colors
  assets/Images/City4.jpg
  assets/Images/Hamilton.jpg
  lib/home.dart
  lib/login.dart
  lib/main.dart
  pubspec.yaml
Labels: documentation

#16 Features : Adding shadow in images tiles
  lib/home.dart
  lib/login.dart
  lib/main.dart
Labels: documentation, enhancement

#17 Add pop ups and fix the text button func
  lib/home.dart
  lib/login.dart
  pubspec.yaml
Labels: documentation, enhancement

#18 Re merging codes and fix some bugs
  lib/home.dart
  lib/login.dart
Labels: bug, documentation, enhancement

#19 feat: Add a navigator menu
  lib/home.dart
Labels: enhancement

#20 fix: drawer wont open
  lib/home.dart
Labels: bug, documentation

#22 feat: Add much more feature
  assets/Images/Facebook.png
  assets/Images/Hamcam.jpg
  assets/Images/Hamilton.png
  assets/Images/Instagram.png
  assets/Images/Mic.jpg
  assets/Images/X.jpg
  assets/Images/Youtube.png
  assets/Images/graduation_hat.jpg
  assets/Images/satisfied.jpg
  assets/Images/yayhamlet.jpg
  lib/home.dart
  lib/main.dart
  pubspec.yaml
Labels: enhancement
